baseurl: "https://jiacheng.site/"
languageCode: "en-us"
title: "Jia Cheng"
theme: "hugo-ivy"
googleAnalytics: "UA-79173423-1"
disqusShortname: "caelan"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100
preserveTaxonomyNames : true
copyright : "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

    
author:
  name : "Jiacheng"
  
permalinks:
  post : "/post/:year/:month/:day/:slug/"
  note : "/note/:year/:month/:day/:slug/"

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/post/"
      weight: 2
    - name: "关于"
      url: "/about/"
      weight: 3
    - name: "分类"
      url: "/categories/"
      weight: 4
    - name: "标签"
      url: "/tags/"
      weight: 5
    - name: "订阅 RSS"
      url: "/post/index.xml"
      weight: 6
    - name: "数据结构系列"
      url: "https://ds.jiacheng.site"
      weight: 7
  

params:
  description: 哦哦~
  footer: "&copy; 2012-2020 | [Jiacheng](/) | [Github](https://github.com/caelanyang)"
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "野比大雄"
    tag: ""
    width: 80
    height: 80


blackfriday:
  extensionsmask: ["noIntraEmphasis"]
  fractions: false
    