baseurl: "https://jiacheng.site/"
languageCode: "en-us"
title: "Jiacheng"
theme: "hugo-ivy"
googleAnalytics: "UA-79173423-1"
disqusShortname: "Caelan"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100
preserveTaxonomyNames : true
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
staticDir: static
    
author:
  name : "Jiacheng"
  
permalinks:
  post: "/post/:year/:month/:day/:slug/"
  note: "/note/:year/:month/:day/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/post/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
    - name: "Cookbook"
      url: "/cookbook/"
      weight: 4
    - name: "Data Structure"
      url: "/data-structure/"
      weight: 5
    - name: ""
      url: ""
      weight: 6
    - name: "RSS"
      url: "/post/index.xml"
      weight: 7
    - name: "License"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
      weight: 8
  

params:
  description: "aha"
  footer: "&copy; 2012-2020 | [Jiacheng](/) | [Github](https://github.com/caelanyang)"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "野比大雄"
    tag: ""
    width: 80
    height: 80

blackfriday:
  extensionsmask: ["noIntraEmphasis"]
  fractions: false



    