baseurl = "https://jiacheng.site/"
languageCode = "zh-cn"
title = "Jia Cheng"
theme = "hugo-ivy"
googleAnalytics = "UA-79173423-1"
disqusShortname = "caelan"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Yang Jiacheng's Home Page."
    footer = "&copy; 2012-2018 | [Yang Jiacheng](https://cheng.netlify.com) | [Github](https://github.com/caelanyang)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
